### ISSUE TITLE
Investigate no_std and wasm size 

### ISSUE THREAD

**Issue by owengage** [owengage/fastnbt#11]
The generated WASM comes in at 1.2 MiB. This comes with an entire palette but that likely takes up a few hundred KiB. Can this be shrunk significantly with anything easy?

Must be a way to see some breakdown of the wasm.

Can we somehow become no_std? Due to doing decompression (ie we don't know the size beforehand) we probably need some for of allocation still.

* try using real palette.tar, but gz it and include as bytes?
* what's preventing no_std?

**Comment by orsenkucher** [comment]
Hi, have you tried optimizing with `wasm-opt`?
```toml
[package.metadata.wasm-pack.profile.release]
# Optimize for size: -Os
# Optimize aggressively for size: -Oz
# Optimize for speed: -O
# Optimize aggressively for speed: -O3
# Trun optimizations off: = false
wasm-opt = ["-Oz", "--enable-mutable-globals"]
```
